# Generated by Django 2.1.7 on 2019-05-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='games_per_person',
            new_name='games_per_person2',
        ),
    ]
