# Generated by Django 2.1.7 on 2019-07-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190509_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(blank=True, null=True, verbose_name='game date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id1',
            field=models.SmallIntegerField(verbose_name='participant1 drawn number'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id2',
            field=models.SmallIntegerField(verbose_name='participant2 drawn number'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='game start time'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='drawn_number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='drawn number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='result1',
            field=models.SmallIntegerField(verbose_name='participant1 result'),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='result2',
            field=models.SmallIntegerField(verbose_name='participant2 result'),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='set_number',
            field=models.SmallIntegerField(verbose_name='set number'),
        ),
    ]
