# Generated by Django 2.1.7 on 2019-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20190722_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='win_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='win_sets',
            field=models.IntegerField(default=0),
        ),
    ]
