# Generated by Django 2.1.7 on 2019-07-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20190728_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='games_left',
            field=models.IntegerField(default=10),
        ),
    ]
